// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An enumeration for the role we are playing
type Role int32

const (
	Role_ROLE_UNKNOWN   Role = 0
	Role_ROLE_VOLUNTEER Role = 1
)

var Role_name = map[int32]string{
	0: "ROLE_UNKNOWN",
	1: "ROLE_VOLUNTEER",
}

var Role_value = map[string]int32{
	"ROLE_UNKNOWN":   0,
	"ROLE_VOLUNTEER": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

// an enumeration for the status of the message request
type Status int32

const (
	Status_STATUS_UNKNOWN     Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_FAILURE     Status = 2
	Status_STATUS_CHECK_AGAIN Status = 3
)

var Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_SUCCESS",
	2: "STATUS_FAILURE",
	3: "STATUS_CHECK_AGAIN",
}

var Status_value = map[string]int32{
	"STATUS_UNKNOWN":     0,
	"STATUS_SUCCESS":     1,
	"STATUS_FAILURE":     2,
	"STATUS_CHECK_AGAIN": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

type MsgTypes int32

const (
	MsgTypes_TYPE_UNKNOWN  MsgTypes = 0
	MsgTypes_TYPE_REGISTER MsgTypes = 1
	MsgTypes_TYPE_JOB      MsgTypes = 2
)

var MsgTypes_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_REGISTER",
	2: "TYPE_JOB",
}

var MsgTypes_value = map[string]int32{
	"TYPE_UNKNOWN":  0,
	"TYPE_REGISTER": 1,
	"TYPE_JOB":      2,
}

func (x MsgTypes) String() string {
	return proto.EnumName(MsgTypes_name, int32(x))
}

func (MsgTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

type CodeMsg struct {
	Requirements         string   `protobuf:"bytes,1,opt,name=requirements,proto3" json:"requirements,omitempty"`
	ProcessCode          string   `protobuf:"bytes,2,opt,name=process_code,json=processCode,proto3" json:"process_code,omitempty"`
	ExecuteCode          string   `protobuf:"bytes,3,opt,name=execute_code,json=executeCode,proto3" json:"execute_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeMsg) Reset()         { *m = CodeMsg{} }
func (m *CodeMsg) String() string { return proto.CompactTextString(m) }
func (*CodeMsg) ProtoMessage()    {}
func (*CodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *CodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeMsg.Unmarshal(m, b)
}
func (m *CodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeMsg.Marshal(b, m, deterministic)
}
func (m *CodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeMsg.Merge(m, src)
}
func (m *CodeMsg) XXX_Size() int {
	return xxx_messageInfo_CodeMsg.Size(m)
}
func (m *CodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CodeMsg proto.InternalMessageInfo

func (m *CodeMsg) GetRequirements() string {
	if m != nil {
		return m.Requirements
	}
	return ""
}

func (m *CodeMsg) GetProcessCode() string {
	if m != nil {
		return m.ProcessCode
	}
	return ""
}

func (m *CodeMsg) GetExecuteCode() string {
	if m != nil {
		return m.ExecuteCode
	}
	return ""
}

type JobMsg struct {
	Jobs                 []string `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobMsg) Reset()         { *m = JobMsg{} }
func (m *JobMsg) String() string { return proto.CompactTextString(m) }
func (*JobMsg) ProtoMessage()    {}
func (*JobMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *JobMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMsg.Unmarshal(m, b)
}
func (m *JobMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMsg.Marshal(b, m, deterministic)
}
func (m *JobMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMsg.Merge(m, src)
}
func (m *JobMsg) XXX_Size() int {
	return xxx_messageInfo_JobMsg.Size(m)
}
func (m *JobMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMsg.DiscardUnknown(m)
}

var xxx_messageInfo_JobMsg proto.InternalMessageInfo

func (m *JobMsg) GetJobs() []string {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type JobResp struct {
	Jobs                 []string `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResp) Reset()         { *m = JobResp{} }
func (m *JobResp) String() string { return proto.CompactTextString(m) }
func (*JobResp) ProtoMessage()    {}
func (*JobResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *JobResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResp.Unmarshal(m, b)
}
func (m *JobResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResp.Marshal(b, m, deterministic)
}
func (m *JobResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResp.Merge(m, src)
}
func (m *JobResp) XXX_Size() int {
	return xxx_messageInfo_JobResp.Size(m)
}
func (m *JobResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResp.DiscardUnknown(m)
}

var xxx_messageInfo_JobResp proto.InternalMessageInfo

func (m *JobResp) GetJobs() []string {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type MainReq struct {
	MsgType MsgTypes `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=MsgTypes" json:"msg_type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*MainReq_JobMsg
	//	*MainReq_CodeMsg
	//	*MainReq_Heartbeat
	Content              isMainReq_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MainReq) Reset()         { *m = MainReq{} }
func (m *MainReq) String() string { return proto.CompactTextString(m) }
func (*MainReq) ProtoMessage()    {}
func (*MainReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *MainReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainReq.Unmarshal(m, b)
}
func (m *MainReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainReq.Marshal(b, m, deterministic)
}
func (m *MainReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainReq.Merge(m, src)
}
func (m *MainReq) XXX_Size() int {
	return xxx_messageInfo_MainReq.Size(m)
}
func (m *MainReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MainReq.DiscardUnknown(m)
}

var xxx_messageInfo_MainReq proto.InternalMessageInfo

func (m *MainReq) GetMsgType() MsgTypes {
	if m != nil {
		return m.MsgType
	}
	return MsgTypes_TYPE_UNKNOWN
}

type isMainReq_Content interface {
	isMainReq_Content()
}

type MainReq_JobMsg struct {
	JobMsg *JobMsg `protobuf:"bytes,2,opt,name=job_msg,json=jobMsg,proto3,oneof"`
}

type MainReq_CodeMsg struct {
	CodeMsg *CodeMsg `protobuf:"bytes,3,opt,name=code_msg,json=codeMsg,proto3,oneof"`
}

type MainReq_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*MainReq_JobMsg) isMainReq_Content() {}

func (*MainReq_CodeMsg) isMainReq_Content() {}

func (*MainReq_Heartbeat) isMainReq_Content() {}

func (m *MainReq) GetContent() isMainReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MainReq) GetJobMsg() *JobMsg {
	if x, ok := m.GetContent().(*MainReq_JobMsg); ok {
		return x.JobMsg
	}
	return nil
}

func (m *MainReq) GetCodeMsg() *CodeMsg {
	if x, ok := m.GetContent().(*MainReq_CodeMsg); ok {
		return x.CodeMsg
	}
	return nil
}

func (m *MainReq) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetContent().(*MainReq_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MainReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MainReq_JobMsg)(nil),
		(*MainReq_CodeMsg)(nil),
		(*MainReq_Heartbeat)(nil),
	}
}

// Response to discovery req will be similar oneof of the responses.
type MainResp struct {
	MsgType MsgTypes `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=MsgTypes" json:"msg_type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*MainResp_JobResp
	//	*MainResp_Heartbeat
	Content              isMainResp_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MainResp) Reset()         { *m = MainResp{} }
func (m *MainResp) String() string { return proto.CompactTextString(m) }
func (*MainResp) ProtoMessage()    {}
func (*MainResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *MainResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MainResp.Unmarshal(m, b)
}
func (m *MainResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MainResp.Marshal(b, m, deterministic)
}
func (m *MainResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainResp.Merge(m, src)
}
func (m *MainResp) XXX_Size() int {
	return xxx_messageInfo_MainResp.Size(m)
}
func (m *MainResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MainResp.DiscardUnknown(m)
}

var xxx_messageInfo_MainResp proto.InternalMessageInfo

func (m *MainResp) GetMsgType() MsgTypes {
	if m != nil {
		return m.MsgType
	}
	return MsgTypes_TYPE_UNKNOWN
}

type isMainResp_Content interface {
	isMainResp_Content()
}

type MainResp_JobResp struct {
	JobResp *JobResp `protobuf:"bytes,2,opt,name=job_resp,json=jobResp,proto3,oneof"`
}

type MainResp_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*MainResp_JobResp) isMainResp_Content() {}

func (*MainResp_Heartbeat) isMainResp_Content() {}

func (m *MainResp) GetContent() isMainResp_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MainResp) GetJobResp() *JobResp {
	if x, ok := m.GetContent().(*MainResp_JobResp); ok {
		return x.JobResp
	}
	return nil
}

func (m *MainResp) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetContent().(*MainResp_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MainResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MainResp_JobResp)(nil),
		(*MainResp_Heartbeat)(nil),
	}
}

func init() {
	proto.RegisterEnum("Role", Role_name, Role_value)
	proto.RegisterEnum("Status", Status_name, Status_value)
	proto.RegisterEnum("MsgTypes", MsgTypes_name, MsgTypes_value)
	proto.RegisterType((*Heartbeat)(nil), "Heartbeat")
	proto.RegisterType((*CodeMsg)(nil), "CodeMsg")
	proto.RegisterType((*JobMsg)(nil), "JobMsg")
	proto.RegisterType((*JobResp)(nil), "JobResp")
	proto.RegisterType((*MainReq)(nil), "MainReq")
	proto.RegisterType((*MainResp)(nil), "MainResp")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x8b, 0x9b, 0x40,
	0x14, 0xc7, 0x63, 0x0c, 0x51, 0x5f, 0xd2, 0x60, 0xe7, 0x50, 0x72, 0x68, 0xa1, 0x95, 0x2e, 0x2c,
	0xa1, 0x78, 0xd8, 0x9e, 0x7b, 0xc8, 0x8a, 0x5d, 0x93, 0x4d, 0x4c, 0x19, 0xb5, 0xa5, 0x50, 0x10,
	0xcd, 0x3e, 0xec, 0x86, 0xea, 0xb8, 0xce, 0x04, 0xba, 0x5f, 0xa2, 0xdf, 0xa5, 0xdf, 0xb0, 0xcc,
	0x38, 0xdb, 0x6e, 0xa0, 0x87, 0xbd, 0x3d, 0x7e, 0xef, 0xaf, 0xef, 0xe7, 0x1f, 0x61, 0x56, 0x23,
	0xe7, 0x45, 0x85, 0xdc, 0x6f, 0x3b, 0x26, 0x98, 0x37, 0x01, 0x27, 0xc2, 0xa2, 0x13, 0x25, 0x16,
	0xc2, 0xe3, 0x60, 0x05, 0xec, 0x06, 0xb7, 0xbc, 0x22, 0x1e, 0x4c, 0x3b, 0xbc, 0x3b, 0xde, 0x76,
	0x58, 0x63, 0x23, 0xf8, 0xdc, 0x78, 0x6d, 0x9c, 0x3b, 0xf4, 0x84, 0x91, 0x37, 0x30, 0x6d, 0x3b,
	0xb6, 0x47, 0xce, 0xf3, 0x3d, 0xbb, 0xc1, 0xf9, 0x50, 0x65, 0x26, 0x9a, 0xc9, 0x37, 0xc9, 0x08,
	0xfe, 0xc4, 0xfd, 0x51, 0x60, 0x1f, 0x31, 0xfb, 0x88, 0x66, 0x32, 0xe2, 0xbd, 0x84, 0xf1, 0x9a,
	0x95, 0xf2, 0x26, 0x81, 0xd1, 0x81, 0x95, 0xf2, 0x96, 0x79, 0xee, 0x50, 0x35, 0x7b, 0xaf, 0xc0,
	0x5a, 0xb3, 0x92, 0x22, 0x6f, 0xff, 0xbb, 0xfe, 0x6d, 0x80, 0xb5, 0x2d, 0x6e, 0x1b, 0x8a, 0x77,
	0xe4, 0x2d, 0xd8, 0x35, 0xaf, 0x72, 0x71, 0xdf, 0xa2, 0xd2, 0x9d, 0x5d, 0x38, 0xfe, 0x96, 0x57,
	0xe9, 0x7d, 0x8b, 0x9c, 0x5a, 0x75, 0x3f, 0x11, 0x0f, 0xac, 0x03, 0x2b, 0xf3, 0x9a, 0x57, 0xca,
	0x77, 0x72, 0x61, 0xf9, 0xfd, 0xf9, 0x68, 0x40, 0xc7, 0x87, 0x5e, 0xe4, 0x0c, 0x6c, 0x69, 0xab,
	0x42, 0xa6, 0x0a, 0xd9, 0xbe, 0x2e, 0x26, 0x1a, 0x50, 0x6b, 0xaf, 0x3b, 0x5a, 0x80, 0xf3, 0xfd,
	0xa1, 0xbb, 0xf9, 0x48, 0xe5, 0xc0, 0xff, 0xdb, 0x66, 0x34, 0xa0, 0xff, 0xd6, 0x97, 0x8e, 0xac,
	0xb6, 0x11, 0xd8, 0x08, 0xef, 0x97, 0x01, 0x76, 0xef, 0xcc, 0xdb, 0x27, 0x4a, 0x9f, 0x81, 0x2d,
	0xa5, 0x3b, 0xe4, 0xad, 0xb6, 0xb6, 0x7d, 0x5d, 0x8b, 0x14, 0x3a, 0xe8, 0x86, 0x4e, 0x84, 0xcc,
	0xa7, 0x0a, 0x2d, 0xde, 0xc1, 0x88, 0xb2, 0x1f, 0x48, 0x5c, 0x98, 0xd2, 0xdd, 0x26, 0xcc, 0xb3,
	0xf8, 0x3a, 0xde, 0x7d, 0x89, 0xdd, 0x01, 0x21, 0x30, 0x53, 0xe4, 0xf3, 0x6e, 0x93, 0xc5, 0x69,
	0x18, 0x52, 0xd7, 0x58, 0x7c, 0x83, 0x71, 0x22, 0x0a, 0x71, 0xe4, 0x72, 0x9b, 0xa4, 0xcb, 0x34,
	0x4b, 0x4e, 0x9f, 0xd0, 0x2c, 0xc9, 0x82, 0x20, 0x4c, 0x12, 0xd7, 0x78, 0xc4, 0x3e, 0x2e, 0x57,
	0x9b, 0x8c, 0x86, 0xee, 0x90, 0xbc, 0x00, 0xa2, 0x59, 0x10, 0x85, 0xc1, 0x75, 0xbe, 0xbc, 0x5a,
	0xae, 0x62, 0xd7, 0x5c, 0x7c, 0x00, 0xfb, 0xe1, 0xf3, 0xa5, 0x4f, 0xfa, 0xf5, 0xd3, 0x63, 0x9f,
	0xe7, 0xf0, 0x4c, 0x11, 0x1a, 0x5e, 0xad, 0x92, 0x54, 0xea, 0x90, 0x29, 0xd8, 0x0a, 0xad, 0x77,
	0x97, 0xee, 0xb0, 0x1c, 0xab, 0xbf, 0xfa, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0x80,
	0x3d, 0xc2, 0xe7, 0x02, 0x00, 0x00,
}
